ALTER TABLE `applications`
    ADD COLUMN `id` int(0) NOT NULL AUTO_INCREMENT FIRST,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`) USING BTREE;

ALTER TABLE `applications`
    MODIFY COLUMN `type` int(255) NOT NULL DEFAULT 1 AFTER `svc_url`;
